# Generated by Django 4.0.1 on 2022-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('Medname', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
